---
title: "Metanalysis of flow state on men caused by (`stMale`)"
author: Geiser C. Challco <geiser@alumni.usp.br>
comment: This file is automatically generate by Shiny-Statistic app (https://statistic.geiser.tech/)
         Author - Geiser C. Challco <geiser@alumni.usp.br>
         
         Shiny-Statistic is distributed in the hope that it will be useful,
         but WITHOUT ANY WARRANTY; without even the implied warranty of
         MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
         GNU General Public License for more details.
         
         You should have received a copy of the GNU General Public License.
         If not, see <https://www.gnu.org/licenses/>.
output:
  html_document:
    toc: true
  word_document:
    toc: true
  github_document:
    toc: true
fontsize: 10pt
---

```{r setup, include=F}
## Install and Load Packages
wants <- c('readxl','meta','metafor','remotes')
has <- wants %in% rownames(installed.packages())
if (any(!has)) install.packages(wants[!has])
if (!"dmetar" %in% rownames(installed.packages())) {
  remotes::install_github("MathiasHarrer/dmetar")
}
library(readxl)

library(meta)
library(dmetar)
library(meta)
```

```{r, include=F, purl=F}
library(knitr)
opts_chunk$set(echo = TRUE)
defaultW <- getOption("warn")
options(warn = -1)
```

## Initial Variables and Loading Data

```{r}
env <- "stMale"
gender <- "men"
to_remove <- c('S11')
sub.groups <- c("age","ed.level","intervention","age:intervention",
                "ed.level:intervention","age:ed.level:intervention")
```

```{r}
dat <- read_excel("../data/data-without-outliers.xlsx", sheet = "fss-env.gender-descriptive")
dat <- dat[!dat$study %in% to_remove, ]

leg <- read_excel("../data/data-without-outliers.xlsx", sheet = "legend")
leg <- leg[!leg$study %in% to_remove, ]

idx.e <- which(dat$env == env & dat$gender == gender)
idx.c <- which(dat$env == "control" & dat$gender == gender)

data <- data.frame(
  study = dat$study[idx.c],
  n.e = dat$N[idx.e], mean.e = dat$M.emms[idx.e], sd.e = dat$SD.emms[idx.e],
  n.c = dat$N[idx.c], mean.c = dat$M.emms[idx.c], sd.c = dat$SD.emms[idx.c]
)
for (cgroups in strsplit(sub.groups,":")) {
  data[[paste0(cgroups, collapse = ":")]] <- sapply(data$study, FUN = function(x) {
    paste0(sapply(cgroups, FUN = function(namecol) leg[[namecol]][which(x == leg$study)]), collapse = ":")
  })
}
data[["lbl"]] <- sapply(data$study, FUN = function(x) leg$Note[which(x == leg$study)])
```

## Perform meta-analyses

```{r}
m.cont <- metacont(
  n.e = n.e, mean.e = mean.e, sd.e = sd.e, n.c = n.c, mean.c = mean.c, sd.c = sd.c,
  studlab = lbl, data = data, sm = "SMD", method.smd = "Hedges",
  fixed = F, random = T, method.tau = "REML", hakn = T, title = paste("Flow state for",gender,"in",env)
)
summary(m.cont)
```

```{r, fig.width=12, fig.height=10, dpi=300}
forest(m.cont, digits=2, digits.sd = 2, test.overall = T, label.e = paste0(gender,':',env))
```

### Subgroup analysis by "age"

```{r}
m.sg4sub <- update.meta(m.cont, subgroup = age, random = T, fixed = F)
summary(m.sg4sub)
```

```{r, fig.width=12, fig.height=10, dpi=300}
forest(m.sg4sub, digits=2, digits.sd = 2, test.overall = T, label.e = paste0(gender,':',env))
```

### Subgroup analysis by "ed.level"

```{r}
m.sg4sub <- update.meta(m.cont, subgroup = ed.level, random = T, fixed = F)
summary(m.sg4sub)
```

```{r, fig.width=12, fig.height=10, dpi=300}
forest(m.sg4sub, digits=2, digits.sd = 2, test.overall = T, label.e = paste0(gender,':',env))
```

### Subgroup analysis by "intervention"

```{r}
m.sg4sub <- update.meta(m.cont, subgroup = intervention, random = T, fixed = F)
summary(m.sg4sub)
```

```{r, fig.width=12, fig.height=10, dpi=300}
forest(m.sg4sub, digits=2, digits.sd = 2, test.overall = T, label.e = paste0(gender,':',env))
```

### Subgroup analysis by "age:intervention"

```{r}
m.sg4sub <- update.meta(m.cont, subgroup = `age:intervention`, random = T, fixed = F)
summary(m.sg4sub)
```

```{r, fig.width=12, fig.height=10, dpi=300}
forest(m.sg4sub, digits=2, digits.sd = 2, test.overall = T, label.e = paste0(gender,':',env))
```

### Subgroup analysis by "ed.level:intervention"

```{r}
m.sg4sub <- update.meta(m.cont, subgroup = `ed.level:intervention`, random = T, fixed = F)
summary(m.sg4sub)
```

```{r, fig.width=12, fig.height=10, dpi=300}
forest(m.sg4sub, digits=2, digits.sd = 2, test.overall = T, label.e = paste0(gender,':',env))
```

### Subgroup analysis by "age:ed.level:intervention"

```{r}
m.sg4sub <- update.meta(m.cont, subgroup = `age:ed.level:intervention`, random = T, fixed = F)
summary(m.sg4sub)
```

```{r, fig.width=12, fig.height=10, dpi=300}
forest(m.sg4sub, digits=2, digits.sd = 2, test.overall = T, label.e = paste0(gender,':',env))
```

## Funnel Plot

```{r}
m.cont <- update.meta(m.cont, studlab = data$study)
summary(eggers.test(x = m.cont))
```

```{r, fig.width=12, fig.height=10, dpi=300}
funnel(m.cont, xlab = "Hedges' g", studlab = T, legend=T, addtau2 = T)
```
